### ISSUE TITLE
How do you dump the requirements.txt?

### ISSUE THREAD

**Issue by sihan-chen-yes** [MarSaKi/NvEM#1]
It seems that your requirements file is just a little bit different from the normal one, I mean your file can't be installed directly.(Or I just don't know how to use this type.) I changed the content so that they can be installed.
absl-py==0.10.0
argon2-cffi==20.1.0
asn1crypto==0.24.0
astroid==2.4.2
async-generator==1.10
attrs==20.2.0
autopep8==1.5.7
backcall==0.2.0
backports.functools-lru-cache==1.4
bcolz==1.2.1
bleach==3.2.1
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
click==7.1.2
cloudpickle==1.3.0
cryptography==2.1.4
cycler==0.10.0
Cython==0.29.21
decorator==4.1.2
defusedxml==0.6.0
easydict==1.9
entrypoints==0.3
future==0.18.2
google-auth==1.21.1
google-auth-oauthlib==0.4.1
grpcio==1.31.0
gym==0.17.2
h5py==2.10.0
idna==2.6
imageio==2.9.0
importlib-metadata==1.7.0
ipykernel==5.3.4
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==5.4.2
jedi==0.17.2
Jinja2==2.11.2
joblib==0.16.0
jsonpatch==1.26
jsonpointer==2.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyterlab-pygments==0.1.2
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==2.1.0
mccabe==0.6.1
mistune==0.8.4
nbclient==0.5.0
nbconvert==6.0.7
nbformat==5.0.7
nest-asyncio==1.4.1
networkx==2.0
nltk==3.5
notebook==6.1.4
numpy==1.19.1
oauthlib==3.1.0
olefile==0.46
opencv-python==4.1.0.25
packaging==20.4
pandas==0.21.0
pandocfilters==1.4.2
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
pip==20.2.2
prometheus-client==0.8.0
prompt-toolkit==3.0.7
protobuf==3.13.0
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.7.0
pycparser==2.20
pycrypto==2.6.1
pyglet==1.5.0
Pygments==2.7.1
pygobject==3.26.1
pylint==2.6.0
pyparsing==2.2.0
pyrsistent==0.17.3
python-dateutil==2.6.1
pytz==2017.3
PyWavelets==1.1.1
pyxdg==0.25
PyYAML==5.3.1
pyzmq==19.0.2
qtconsole==4.7.7
QtPy==1.9.0
regex==2020.7.14
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.17.2
scipy==1.2.1
SecretStorage==2.3.1
Send2Trash==1.5.0
setuptools==50.3.0
six==1.11.0
ssh-import-id==5.7
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
terminado==0.9.1
testpath==0.4.4
tifffile==2020.8.25
toml==0.10.1
torch==0.4.0
torchfile==0.1.0
torchvision==0.1.8
tornado==6.0.4
tqdm==4.48.2
traitlets==4.3.3
typed-ast==1.4.1
urllib3==1.22
visdom==0.1.8.9
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==1.0.1
wheel==0.30.0
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0

**Comment by MarSaKi** [comment]
Thanks for your attention!
You're right. My requirements.txt was not generated for direct installation, but your modification makes it work.
I forget how to generate the txt file.

**Comment by MarSaKi** [comment]
I dumped it by:
`pip list >> requirements.txt`

**Comment by sihan-chen-yes** [comment]
Thanks for your reply.
maybe you could try the cmd:
pip list --format=freeze > requirements.txt

**Comment by MarSaKi** [comment]
Thanks a lot, I will try it.
